language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode # JRuby in 1.8 mode
  - ree
# Fails:
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode
#  - jruby-head
before_install: gem install rspec
script: rspec spec
